# Generated by Django 4.1.7 on 2023-03-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Kategroiya nomi en')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Kategroiyalar',
                'verbose_name_plural': 'Kategroiyalar',
            },
        ),
        migrations.CreateModel(
            name='GlobCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='kategroiya nomi en')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Kategroiyalar',
                'verbose_name_plural': 'Kategroiyalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('lang', models.CharField(max_length=2, verbose_name='Tili')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Raqam')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Tovar nomi en')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Tovar nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Tovar nomi en')),
                ('descr_uz', models.TextField(verbose_name="Tovar ma'lumotlari en")),
                ('descr_ru', models.TextField(verbose_name="Tovar ma'lumotlari ru")),
                ('descr_en', models.TextField(verbose_name="Tovar ma'lumotlari en")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serio_app.category', verbose_name='Tovar kategoriyasi')),
            ],
            options={
                'verbose_name': 'Tovarlar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='glob_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serio_app.globcat', verbose_name='Bosh kategoriya'),
        ),
    ]
