# Generated by Django 4.2.2 on 2023-06-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Xizmat turlari',
                'verbose_name_plural': 'Xizmat turlari',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=200, verbose_name='Kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Kategroiya nomi en')),
            ],
            options={
                'verbose_name': 'Kategroiyalar',
                'verbose_name_plural': 'Kategroiyalar',
            },
        ),
        migrations.CreateModel(
            name='GlobCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=200, verbose_name='kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='kategroiya nomi en')),
            ],
            options={
                'verbose_name': 'Bosh kategroiyalar',
                'verbose_name_plural': 'Bosh kategroiyalar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Viloyatlar',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('lang', models.CharField(max_length=2, verbose_name='Tili')),
                ('role', models.CharField(max_length=100, null=True, verbose_name='Soha')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Raqam')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('phone', models.CharField(max_length=100, verbose_name='Raqam')),
                ('weight', models.CharField(max_length=100, verbose_name="Og'irligi")),
                ('brock', models.ManyToManyField(to='serio_app.brock', verbose_name='Xizmat')),
                ('region', models.ManyToManyField(to='serio_app.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Xizmatchilar',
                'verbose_name_plural': 'Xizmatchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=200, verbose_name='Tovar nomi en')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Tovar nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Tovar nomi en')),
                ('price', models.CharField(max_length=100, verbose_name='Tovar narxi')),
                ('descr_uz', models.TextField(verbose_name="Tovar ma'lumotlari en")),
                ('descr_ru', models.TextField(verbose_name="Tovar ma'lumotlari ru")),
                ('descr_en', models.TextField(verbose_name="Tovar ma'lumotlari en")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serio_app.category', verbose_name='Tovar kategoriyasi')),
            ],
            options={
                'verbose_name': 'Tovarlar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='glob_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serio_app.globcat', verbose_name='Bosh kategoriya'),
        ),
    ]
