# Generated by Django 4.2.2 on 2023-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brock',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi en'),
        ),
        migrations.AlterField(
            model_name='brock',
            name='name_ru',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi ru'),
        ),
        migrations.AlterField(
            model_name='brock',
            name='name_uz',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi uz'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi en'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi ru'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi uz'),
        ),
    ]
