# Generated by Django 4.1.7 on 2023-03-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globcat',
            options={'verbose_name': 'Bosh kategroiyalar', 'verbose_name_plural': 'Bosh kategroiyalar'},
        ),
    ]
