# Generated by Django 4.1.7 on 2023-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0002_alter_globcat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=100, verbose_name='Tovar narxi'),
            preserve_default=False,
        ),
    ]
