# Generated by Django 4.2.2 on 2023-06-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0002_alter_brock_name_en_alter_brock_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='glob_cat',
        ),
        migrations.AddField(
            model_name='product',
            name='analog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serio_app.product', verbose_name='Analog'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serio_app.region', verbose_name='Tovar hududi'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GlobCat',
        ),
    ]
