# Generated by Django 4.2.2 on 2023-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=100, verbose_name='Soha'),
            preserve_default=False,
        ),
    ]
