# Generated by Django 4.2.2 on 2023-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='Soha'),
        ),
    ]
