# Generated by Django 4.1.7 on 2023-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0005_product_phone_alter_product_analog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descr_en',
            field=models.TextField(blank=True, null=True, verbose_name="Tovar ma'lumotlari en"),
        ),
        migrations.AlterField(
            model_name='product',
            name='descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Tovar ma'lumotlari ru"),
        ),
        migrations.AlterField(
            model_name='product',
            name='descr_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Tovar ma'lumotlari en"),
        ),
        migrations.AlterField(
            model_name='service',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Og'irligi"),
        ),
    ]
