# Generated by Django 4.1.7 on 2023-07-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0006_alter_product_descr_en_alter_product_descr_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=200, verbose_name='Kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Kategroiya nomi en')),
            ],
            options={
                'verbose_name': 'Bosh Kategroiyalar',
                'verbose_name_plural': 'Bosh Kategroiyalar',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.CharField(max_length=100, null=True, verbose_name='Tovar ishlab chiqarligan shahar'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name_uz', models.CharField(max_length=200, verbose_name='Kategroiya nomi uz')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Kategroiya nomi ru')),
                ('name_en', models.CharField(max_length=200, verbose_name='Kategroiya nomi en')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serio_app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kichik Kategroiyalar',
                'verbose_name_plural': 'Kichik Kategroiyalar',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='glob_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serio_app.globcategory', verbose_name='Bosh kategoriya'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serio_app.subcategory', verbose_name='Tovar kategoriyasi'),
        ),
    ]
