# Generated by Django 4.2.2 on 2023-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0006_brock_region_category_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brock',
            options={'verbose_name': 'Xizmat turlari', 'verbose_name_plural': 'Xizmat turlari'},
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nomi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('phone', models.CharField(max_length=100, verbose_name='Raqam')),
                ('weight', models.CharField(max_length=100, verbose_name="Og'irligi")),
                ('brock', models.ManyToManyField(to='serio_app.brock', verbose_name='Xizmat')),
                ('region', models.ManyToManyField(to='serio_app.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Xizmatchilar',
                'verbose_name_plural': 'Xizmatchilar',
            },
        ),
    ]
