# Generated by Django 4.1.7 on 2023-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0007_globcategory_remove_product_category_product_made_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/no-photo_5TKbPdH.png', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
