# Generated by Django 4.1.7 on 2023-07-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0008_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Rasimlar', 'verbose_name_plural': 'Rasimalar'},
        ),
    ]
