# Generated by Django 4.1.7 on 2023-07-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serio_app', '0009_alter_images_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brock',
            name='image',
            field=models.ImageField(default='media/no-photo_5TKbPdH.png', upload_to=''),
        ),
    ]
